gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Me sorry to keep waiting!\p"
	.string "Welcome to world of BEYTAH!\p"
	.string "Me name KONKEY DONG.\p"
	.string "But everyone call me the BEYTAH\n"
	.string "PROFESSOR!\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This am “BEYTAH POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "BEYTAH POKAMAN is bettah\n"
	.string "den tha FINAL POKAMAN!\p"
	.string "BEYTAH BEYTAH BEYTAH\n"
	.string "ME LIKE BEYTAH POKAMAN GAME\l"
	.string "ME NEED MORE BEYTAH BETTA BEYTAH\p"
	.string "BEYTAH BETTAH EVERY TIME!\p"
	.string "ME WANT BEYTAH RIGHT NOW\n"
	.string "ME NO USE SEARCH TOOL OR\l"
	.string "PINNED MESSAGE OR READ FAQ\p"
	.string "ME JUST WANT BEYTAH BECAUSE\n"
	.string "BEYTAH BETTAH THAN FINAL\l"
	.string "HOW TO USE CVS ME DELETE V AND\p"
	.string "ME SEE NO BEYTAH GIVE ME BEYTAH\n"
	.string "RIGHT NOW ME CANNOT DO MYSELF!\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "Anyway, who you?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you boy?\n"
	.string "Or are you “girl”?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What you name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "OK!\p"
	.string "You {PLAYER}{KUN} who moving to\n"
	.string "LEAK ISLAND.\l"
	.string "Me get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "Okay, are you ready?\p"
	.string "Your beytah adventure am\n"
	.string "begin to unfold!\p"
	.string "If you find BEYTAH, please\n"
	.string "bring me BEYTAH!\l"
	.string "Me love BEYTAH!\p"
	.string "Visit my LAB after you\n"
	.string "set your CLOCK!\p"
	.string "$"
